# Basic dependabot.yml to update gomod and GitHub Actions

version: 2
updates:
  - package-ecosystem: "gomod"
    target-branch: "master"
    directory: "/"
    schedule:
      interval: "daily"
      # Check for npm updates at 9am UTC (5am EST)
      time: "10:00"
    reviewers:
      - "habibrosyad"
    assignees:
      - "habibrosyad"
    # Labels must be created first
    labels:
      - "update"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    target-branch: "master"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "habibrosyad"
    assignees:
      - "habibrosyad"
    labels:
      - "chore"
    open-pull-requests-limit: 10
